/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mysqlservice.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mysqlservice.model.Chusohuu;
import com.mysqlservice.model.ChusohuuModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Chusohuu service. Represents a row in the &quot;Mysql_Chusohuu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ChusohuuModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChusohuuImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChusohuuImpl
 * @generated
 */
public class ChusohuuModelImpl
	extends BaseModelImpl<Chusohuu> implements ChusohuuModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chusohuu model instance should use the <code>Chusohuu</code> interface instead.
	 */
	public static final String TABLE_NAME = "Mysql_Chusohuu";

	public static final Object[][] TABLE_COLUMNS = {
		{"pid", Types.INTEGER}, {"pchusohuu", Types.VARCHAR},
		{"pthunuoi", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("pid", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("pchusohuu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pthunuoi", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Mysql_Chusohuu (pid INTEGER not null primary key,pchusohuu VARCHAR(75) null,pthunuoi INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table Mysql_Chusohuu";

	public static final String ORDER_BY_JPQL = " ORDER BY chusohuu.pid ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Mysql_Chusohuu.pid ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ChusohuuModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _pid;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setPid(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _pid;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Chusohuu.class;
	}

	@Override
	public String getModelClassName() {
		return Chusohuu.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Chusohuu, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Chusohuu, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Chusohuu, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Chusohuu)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Chusohuu, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Chusohuu, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Chusohuu)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Chusohuu, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Chusohuu, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Chusohuu, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Chusohuu, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Chusohuu, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Chusohuu, Object>>();
		Map<String, BiConsumer<Chusohuu, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Chusohuu, ?>>();

		attributeGetterFunctions.put("pid", Chusohuu::getPid);
		attributeSetterBiConsumers.put(
			"pid", (BiConsumer<Chusohuu, Integer>)Chusohuu::setPid);
		attributeGetterFunctions.put("pchusohuu", Chusohuu::getPchusohuu);
		attributeSetterBiConsumers.put(
			"pchusohuu", (BiConsumer<Chusohuu, String>)Chusohuu::setPchusohuu);
		attributeGetterFunctions.put("pthunuoi", Chusohuu::getPthunuoi);
		attributeSetterBiConsumers.put(
			"pthunuoi", (BiConsumer<Chusohuu, Integer>)Chusohuu::setPthunuoi);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getPid() {
		return _pid;
	}

	@Override
	public void setPid(int pid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pid = pid;
	}

	@Override
	public String getPchusohuu() {
		if (_pchusohuu == null) {
			return "";
		}
		else {
			return _pchusohuu;
		}
	}

	@Override
	public void setPchusohuu(String pchusohuu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pchusohuu = pchusohuu;
	}

	@Override
	public int getPthunuoi() {
		return _pthunuoi;
	}

	@Override
	public void setPthunuoi(int pthunuoi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pthunuoi = pthunuoi;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Chusohuu toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Chusohuu>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChusohuuImpl chusohuuImpl = new ChusohuuImpl();

		chusohuuImpl.setPid(getPid());
		chusohuuImpl.setPchusohuu(getPchusohuu());
		chusohuuImpl.setPthunuoi(getPthunuoi());

		chusohuuImpl.resetOriginalValues();

		return chusohuuImpl;
	}

	@Override
	public Chusohuu cloneWithOriginalValues() {
		ChusohuuImpl chusohuuImpl = new ChusohuuImpl();

		chusohuuImpl.setPid(this.<Integer>getColumnOriginalValue("pid"));
		chusohuuImpl.setPchusohuu(
			this.<String>getColumnOriginalValue("pchusohuu"));
		chusohuuImpl.setPthunuoi(
			this.<Integer>getColumnOriginalValue("pthunuoi"));

		return chusohuuImpl;
	}

	@Override
	public int compareTo(Chusohuu chusohuu) {
		int primaryKey = chusohuu.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Chusohuu)) {
			return false;
		}

		Chusohuu chusohuu = (Chusohuu)object;

		int primaryKey = chusohuu.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Chusohuu> toCacheModel() {
		ChusohuuCacheModel chusohuuCacheModel = new ChusohuuCacheModel();

		chusohuuCacheModel.pid = getPid();

		chusohuuCacheModel.pchusohuu = getPchusohuu();

		String pchusohuu = chusohuuCacheModel.pchusohuu;

		if ((pchusohuu != null) && (pchusohuu.length() == 0)) {
			chusohuuCacheModel.pchusohuu = null;
		}

		chusohuuCacheModel.pthunuoi = getPthunuoi();

		return chusohuuCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Chusohuu, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Chusohuu, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Chusohuu, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Chusohuu)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Chusohuu, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Chusohuu, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Chusohuu, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Chusohuu)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Chusohuu>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Chusohuu.class, ModelWrapper.class);

	}

	private int _pid;
	private String _pchusohuu;
	private int _pthunuoi;

	public <T> T getColumnValue(String columnName) {
		Function<Chusohuu, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Chusohuu)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("pid", _pid);
		_columnOriginalValues.put("pchusohuu", _pchusohuu);
		_columnOriginalValues.put("pthunuoi", _pthunuoi);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("pid", 1L);

		columnBitmasks.put("pchusohuu", 2L);

		columnBitmasks.put("pthunuoi", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Chusohuu _escapedModel;

}