/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mysqlservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Chusohuu service. Represents a row in the &quot;Mysql_Chusohuu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mysqlservice.model.impl.ChusohuuModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mysqlservice.model.impl.ChusohuuImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Chusohuu
 * @generated
 */
@ProviderType
public interface ChusohuuModel extends BaseModel<Chusohuu> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chusohuu model instance should use the {@link Chusohuu} interface instead.
	 */

	/**
	 * Returns the primary key of this chusohuu.
	 *
	 * @return the primary key of this chusohuu
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this chusohuu.
	 *
	 * @param primaryKey the primary key of this chusohuu
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the pid of this chusohuu.
	 *
	 * @return the pid of this chusohuu
	 */
	public int getPid();

	/**
	 * Sets the pid of this chusohuu.
	 *
	 * @param pid the pid of this chusohuu
	 */
	public void setPid(int pid);

	/**
	 * Returns the pchusohuu of this chusohuu.
	 *
	 * @return the pchusohuu of this chusohuu
	 */
	@AutoEscape
	public String getPchusohuu();

	/**
	 * Sets the pchusohuu of this chusohuu.
	 *
	 * @param pchusohuu the pchusohuu of this chusohuu
	 */
	public void setPchusohuu(String pchusohuu);

	/**
	 * Returns the pthunuoi of this chusohuu.
	 *
	 * @return the pthunuoi of this chusohuu
	 */
	public int getPthunuoi();

	/**
	 * Sets the pthunuoi of this chusohuu.
	 *
	 * @param pthunuoi the pthunuoi of this chusohuu
	 */
	public void setPthunuoi(int pthunuoi);

	@Override
	public Chusohuu cloneWithOriginalValues();

}